
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ThingsLostAndFound.Models
{

using System;
    using System.Collections.Generic;
    
public partial class LostAndFoundObject
{

    public int Id { get; set; }

    public Nullable<int> UserIdreportedLost { get; set; }

    public Nullable<int> UserIdreportFound { get; set; }

    public System.DateTime date { get; set; }

    public Nullable<int> ObjectIDLost { get; set; }

    public Nullable<int> ObjectIDFound { get; set; }

    public string ContactNameuser { get; set; }



    public virtual InfoUser InfoUser { get; set; }

    public virtual InfoUser InfoUser1 { get; set; }

    public virtual FoundObject FoundObject { get; set; }

    public virtual LostObject LostObject { get; set; }

}

}
