//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThingsLostAndFound.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Message()
        {
            this.InfoUsers = new HashSet<InfoUser>();
        }
    
        public int Id { get; set; }
        public Nullable<bool> NewMessage { get; set; }
        public string SupportMessages { get; set; }
        public Nullable<int> RefMessagesContactUsersDontRegistered { get; set; }
        public Nullable<int> RefMessagesContactUsersRegistered { get; set; }
        public Nullable<int> MessageNumbers { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoUser> InfoUsers { get; set; }
    }
}
