
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ThingsLostAndFound.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Setting
{

    public int Id { get; set; }

    public bool NewObject { get; set; }

    public bool EditObject { get; set; }

    public bool DeleteObject { get; set; }

    public bool NewUser { get; set; }

    public bool EditUser { get; set; }

    public bool DeleteUser { get; set; }

    public bool ChangePass { get; set; }

    public bool SendPass { get; set; }

    public bool SendMsgFoUserNR { get; set; }

    public bool SendMsgFoUserReg { get; set; }

    public bool SendMsgLoUserNR { get; set; }

    public bool SendMsgLoUserReg { get; set; }

    public bool EmailMsgs { get; set; }

}

}
