
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ThingsLostAndFound.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Setting
{

    public int Id { get; set; }

    public Nullable<bool> NewObject { get; set; }

    public Nullable<bool> EditObject { get; set; }

    public Nullable<bool> DeleteObject { get; set; }

    public Nullable<bool> NewUser { get; set; }

    public Nullable<bool> EditUser { get; set; }

    public Nullable<bool> DeleteUser { get; set; }

}

}
