

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ThingsLostAndFound.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class TLAFEntities : DbContext
{
    public TLAFEntities()
        : base("name=TLAFEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<InfoUser> InfoUsers { get; set; }

    public virtual DbSet<FoundObject> FoundObjects { get; set; }

    public virtual DbSet<LostAndFoundObject> LostAndFoundObjects { get; set; }

    public virtual DbSet<LostObject> LostObjects { get; set; }

    public virtual DbSet<File> Files { get; set; }

    public virtual DbSet<Message> Messages { get; set; }

    public virtual DbSet<Setting> Settings { get; set; }

}

}

