//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThingsLostAndFound.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersContactDontRegister
    {
        public int Id { get; set; }
        public int UserIdRequestLost { get; set; }
        public int UserIdReportFound { get; set; }
        public string Message1 { get; set; }
        public string UserEmailRequestLost { get; set; }
        public Nullable<System.DateTime> DateSendEmail { get; set; }
        public int ObjectIdFound { get; set; }
    
        public virtual FoundObject FoundObject { get; set; }
    }
}
